language: go
sudo: false
os:
  - osx
  - linux
go:
  - 1.12.x
env:
  - GO111MODULE=on
install: true
before_install:
  - go get github.com/mattn/goveralls
script:
  - go build .
  - $GOPATH/bin/goveralls -service=travis-ci